import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'

// ─── Data ─────────────────────────────────────────────────────────────────────
const STATS = [
  { value: '12', label: 'Components', sub: 'AI scaffolded' },
  { value: '3',  label: 'API Routes',  sub: 'Generated by Copilot' },
  { value: '847',label: 'Lines',       sub: 'AI written' },
  { value: '0',  label: 'Stack Overflow', sub: 'visits needed' },
]

const PROMPTS = [
  {
    id: 1,
    file: 'azureOpenAI.service.js',
    prompt: 'Build a complete mystery generator API using Azure OpenAI that returns structured JSON with suspects, evidence, locations, and a hidden truth. Include interrogation and accusation evaluation functions.',
    output: 'Generated azureOpenAI.service.js with 3 AI functions (generateMystery, interrogateSuspect, evaluateAccusation)',
    tag: 'Backend · Node.js',
    tagColor: '#22C55E',
  },
  {
    id: 2,
    file: 'TheoryBoard.jsx',
    prompt: 'Create a cork board Theory Board with draggable cards using Framer Motion, SVG red string connections between cards, and a murder board texture. Cards for suspects, evidence, and sticky notes.',
    output: 'Generated TheoryBoard.jsx with Framer Motion drag, SVG bezier connections, and cork board CSS gradient',
    tag: 'Frontend · React',
    tagColor: '#3B82F6',
  },
  {
    id: 3,
    file: 'Interrogation.jsx',
    prompt: 'Build an interrogation room where the AI responds in-character as a suspect based on their personality, alibi, and guilt status. Include conversation memory, mood tracking, and a typing indicator.',
    output: 'Generated Interrogation.jsx with full conversation history, mood state, clue discovery toasts, and animated typing dots',
    tag: 'Frontend · React',
    tagColor: '#3B82F6',
  },
]

const TECH_STACK = [
  { name: 'React 18',       icon: '⚛️',  color: '#61DAFB' },
  { name: 'Azure OpenAI',   icon: '🤖',  color: '#0078D4' },
  { name: 'Firebase',       icon: '🔥',  color: '#FFA000' },
  { name: 'Framer Motion',  icon: '🎞️',  color: '#BB22D9' },
  { name: 'Tailwind CSS',   icon: '🎨',  color: '#06B6D4' },
  { name: 'Node.js',        icon: '🟢',  color: '#22C55E' },
  { name: 'Vite',           icon: '⚡',  color: '#646CFF' },
  { name: 'Zustand',        icon: '🐻',  color: '#FF9900' },
]

// ─── Shared animation variants ────────────────────────────────────────────────
const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: 'easeOut' } },
}
const stagger = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.1 } },
}

// ─── Octocat SVG ──────────────────────────────────────────────────────────────
function OctocatIcon({ size = 80 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
      <circle cx="16" cy="16" r="16" fill="#22C55E" opacity="0.15" />
      <text x="50%" y="55%" dominantBaseline="middle" textAnchor="middle" fontSize="20">🐙</text>
    </svg>
  )
}

// ─── Prompt Card ──────────────────────────────────────────────────────────────
function PromptCard({ p, index }) {
  return (
    <motion.div
      variants={fadeUp}
      style={{
        backgroundColor: '#0D1117',
        border: '1px solid #30363D',
        borderRadius: 12,
        overflow: 'hidden',
      }}
    >
      {/* Editor title bar */}
      <div style={{
        backgroundColor: '#161B22',
        borderBottom: '1px solid #30363D',
        padding: '10px 16px',
        display: 'flex',
        alignItems: 'center',
        gap: 12,
      }}>
        {/* Traffic lights */}
        <div style={{ display: 'flex', gap: 6 }}>
          {['#FF5F57', '#FEBC2E', '#28C840'].map((c) => (
            <div key={c} style={{ width: 11, height: 11, borderRadius: '50%', backgroundColor: c }} />
          ))}
        </div>
        <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: '#8B949E' }}>
          {p.file}
        </span>
        <div style={{ marginLeft: 'auto' }}>
          <span style={{
            fontSize: 10,
            fontWeight: 600,
            color: p.tagColor,
            backgroundColor: `${p.tagColor}18`,
            border: `1px solid ${p.tagColor}40`,
            borderRadius: 9999,
            padding: '2px 10px',
            fontFamily: 'Inter, sans-serif',
          }}>
            {p.tag}
          </span>
        </div>
      </div>

      <div style={{ padding: '20px 20px 18px' }}>
        {/* Prompt label */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: '#8B949E', letterSpacing: '0.08em', textTransform: 'uppercase', fontFamily: 'Inter, sans-serif' }}>
            Prompt #{index + 1}
          </span>
        </div>

        {/* Prompt text */}
        <div style={{
          backgroundColor: '#0A0F16',
          border: '1px solid #21262D',
          borderRadius: 8,
          padding: '12px 14px',
          marginBottom: 14,
          position: 'relative',
        }}>
          <span style={{
            position: 'absolute',
            top: 10,
            left: 14,
            fontSize: 12,
            color: '#22C55E',
            fontFamily: 'JetBrains Mono, monospace',
          }}>
            &gt;{' '}
          </span>
          <p style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 12,
            color: '#C9D1D9',
            lineHeight: 1.75,
            paddingLeft: 18,
            margin: 0,
          }}>
            {p.prompt}
          </p>
        </div>

        {/* Output */}
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 8 }}>
          <span style={{ fontSize: 14, flexShrink: 0, marginTop: 1 }}>✅</span>
          <p style={{
            fontFamily: 'JetBrains Mono, monospace',
            fontSize: 11,
            color: '#22C55E',
            lineHeight: 1.65,
            margin: 0,
          }}>
            {p.output}
          </p>
        </div>
      </div>
    </motion.div>
  )
}

// ─── Main Page ────────────────────────────────────────────────────────────────
export default function CopilotShowcase() {
  const navigate = useNavigate()

  return (
    <div style={{
      backgroundColor: '#0D1117',
      minHeight: '100vh',
      color: '#C9D1D9',
      fontFamily: 'Inter, sans-serif',
      overflowX: 'hidden',
    }}>

      {/* Top nav */}
      <div style={{
        backgroundColor: 'rgba(13,17,23,0.95)',
        backdropFilter: 'blur(8px)',
        borderBottom: '1px solid #21262D',
        padding: '12px 32px',
        display: 'flex',
        alignItems: 'center',
        gap: 16,
        position: 'sticky',
        top: 0,
        zIndex: 10,
      }}>
        <motion.button
          whileHover={{ scale: 1.06 }}
          whileTap={{ scale: 0.94 }}
          onClick={() => navigate('/')}
          style={{ background: 'none', border: 'none', color: '#8B949E', cursor: 'pointer', fontSize: 16, padding: 0 }}
        >
          ←
        </motion.button>
        <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, color: '#58A6FF' }}>mysteria-ai</span>
        <span style={{ color: '#30363D' }}>/</span>
        <span style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, color: '#C9D1D9' }}>copilot-showcase</span>
        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 8 }}>
          <div style={{ width: 8, height: 8, borderRadius: '50%', backgroundColor: '#22C55E' }} />
          <span style={{ fontSize: 12, color: '#8B949E' }}>Built at Microsoft Agents League 2024</span>
        </div>
      </div>

      <div style={{ maxWidth: 1000, margin: '0 auto', padding: '72px 32px 120px' }}>

        {/* ══════════ HERO ══════════ */}
        <motion.section
          variants={stagger}
          initial="hidden"
          animate="visible"
          style={{ textAlign: 'center', marginBottom: 80 }}
        >
          <motion.div variants={fadeUp} style={{ marginBottom: 28 }}>
            <motion.div
              animate={{ rotate: [0, -8, 8, -8, 0] }}
              transition={{ duration: 2, delay: 0.8, repeat: Infinity, repeatDelay: 4 }}
              style={{ fontSize: 72, lineHeight: 1, display: 'inline-block' }}
            >
              🐙
            </motion.div>
          </motion.div>

          <motion.div variants={fadeUp}>
            <span style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              backgroundColor: 'rgba(34,197,94,0.1)',
              border: '1px solid rgba(34,197,94,0.3)',
              borderRadius: 9999,
              padding: '5px 16px',
              fontSize: 12,
              color: '#22C55E',
              fontFamily: 'JetBrains Mono, monospace',
              marginBottom: 24,
            }}>
              ● github/copilot — active
            </span>
          </motion.div>

          <motion.h1
            variants={fadeUp}
            style={{
              fontFamily: 'Cinzel, serif',
              fontSize: 'clamp(2rem, 5vw, 3.2rem)',
              fontWeight: 700,
              color: '#F0F6FC',
              marginBottom: 16,
              lineHeight: 1.15,
            }}
          >
            Built with GitHub Copilot
          </motion.h1>

          <motion.p
            variants={fadeUp}
            style={{
              fontSize: 16,
              color: '#8B949E',
              lineHeight: 1.75,
              maxWidth: 560,
              margin: '0 auto',
            }}
          >
            Every component, every API route, every animation was scaffolded using AI.
            From a single paragraph prompt to production-ready code.
          </motion.p>
        </motion.section>

        {/* ══════════ STATS ══════════ */}
        <motion.section
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          style={{ marginBottom: 80 }}
        >
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 16 }}>
            {STATS.map((s) => (
              <motion.div
                key={s.label}
                variants={fadeUp}
                whileHover={{ y: -4, borderColor: 'rgba(34,197,94,0.5)' }}
                style={{
                  backgroundColor: '#161B22',
                  border: '1px solid #30363D',
                  borderRadius: 12,
                  padding: '24px 20px',
                  textAlign: 'center',
                  transition: 'border-color 0.2s',
                }}
              >
                <p style={{
                  fontFamily: 'JetBrains Mono, monospace',
                  fontSize: 36,
                  fontWeight: 700,
                  color: '#22C55E',
                  marginBottom: 6,
                  lineHeight: 1,
                }}>
                  {s.value}
                </p>
                <p style={{ fontSize: 14, fontWeight: 600, color: '#F0F6FC', marginBottom: 4 }}>{s.label}</p>
                <p style={{ fontSize: 12, color: '#8B949E' }}>{s.sub}</p>
              </motion.div>
            ))}
          </div>
        </motion.section>

        {/* ══════════ PROMPTS ══════════ */}
        <motion.section
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: '-40px' }}
          style={{ marginBottom: 80 }}
        >
          <motion.div variants={fadeUp} style={{ marginBottom: 36 }}>
            <h2 style={{
              fontFamily: 'Cinzel, serif',
              fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
              color: '#F0F6FC',
              marginBottom: 8,
            }}>
              Prompts That Built This App
            </h2>
            <p style={{ fontSize: 13, color: '#8B949E' }}>
              Real prompts used in this hackathon project — verbatim.
            </p>
          </motion.div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {PROMPTS.map((p, i) => (
              <PromptCard key={p.id} p={p} index={i} />
            ))}
          </div>
        </motion.section>

        {/* ══════════ QUOTE ══════════ */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.65 }}
          style={{ marginBottom: 80 }}
        >
          <div style={{
            backgroundColor: '#161B22',
            border: '1px solid #30363D',
            borderLeft: '4px solid #22C55E',
            borderRadius: '0 12px 12px 0',
            padding: '32px 36px',
            position: 'relative',
            overflow: 'hidden',
          }}>
            {/* Background quote mark */}
            <div style={{
              position: 'absolute',
              top: -10,
              left: 20,
              fontSize: 120,
              color: 'rgba(34,197,94,0.06)',
              fontFamily: 'Georgia, serif',
              lineHeight: 1,
              pointerEvents: 'none',
            }}>
              "
            </div>

            <p style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: 'clamp(14px, 2vw, 17px)',
              color: '#C9D1D9',
              lineHeight: 1.85,
              marginBottom: 20,
              fontStyle: 'italic',
              position: 'relative',
            }}>
              "GitHub Copilot didn't just autocomplete — it architected entire features from a single paragraph prompt.
              What would have taken days of boilerplate took minutes. The detective game you're playing right now
              exists because of AI-assisted development."
            </p>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <div style={{
                width: 32,
                height: 32,
                borderRadius: '50%',
                backgroundColor: 'rgba(34,197,94,0.2)',
                border: '1px solid rgba(34,197,94,0.4)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: 16,
              }}>
                🐙
              </div>
              <div>
                <p style={{ fontSize: 13, fontWeight: 600, color: '#F0F6FC', margin: 0 }}>Team Mysteria AI</p>
                <p style={{ fontSize: 12, color: '#8B949E', margin: 0 }}>Microsoft Agents League 2024</p>
              </div>
            </div>
          </div>
        </motion.section>

        {/* ══════════ TECH STACK ══════════ */}
        <motion.section
          variants={stagger}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
        >
          <motion.h2
            variants={fadeUp}
            style={{
              fontFamily: 'Cinzel, serif',
              fontSize: 'clamp(1.3rem, 3vw, 1.8rem)',
              color: '#F0F6FC',
              marginBottom: 8,
            }}
          >
            Tech Stack
          </motion.h2>
          <motion.p variants={fadeUp} style={{ fontSize: 13, color: '#8B949E', marginBottom: 32 }}>
            Every tool in this stack was used and integrated with Copilot assistance.
          </motion.p>

          <motion.div
            variants={stagger}
            style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))', gap: 12 }}
          >
            {TECH_STACK.map((tech) => (
              <motion.div
                key={tech.name}
                variants={fadeUp}
                whileHover={{ scale: 1.04, borderColor: `${tech.color}60` }}
                style={{
                  backgroundColor: '#161B22',
                  border: '1px solid #30363D',
                  borderRadius: 10,
                  padding: '14px 16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 12,
                  transition: 'border-color 0.2s',
                }}
              >
                <span style={{ fontSize: 22 }}>{tech.icon}</span>
                <div>
                  <p style={{ fontSize: 13, fontWeight: 600, color: '#F0F6FC', margin: 0 }}>{tech.name}</p>
                  <div style={{ width: 28, height: 2, backgroundColor: tech.color, borderRadius: 9999, marginTop: 4, opacity: 0.7 }} />
                </div>
              </motion.div>
            ))}
          </motion.div>

          {/* Footer line */}
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: 0.4 }}
            style={{ marginTop: 64, textAlign: 'center', borderTop: '1px solid #21262D', paddingTop: 40 }}
          >
            <p style={{ fontFamily: 'JetBrains Mono, monospace', fontSize: 13, color: '#8B949E', marginBottom: 8 }}>
              <span style={{ color: '#22C55E' }}>●</span> powered by{' '}
              <span style={{ color: '#58A6FF' }}>Azure AI Foundry</span> ·{' '}
              <span style={{ color: '#58A6FF' }}>Foundry IQ</span> ·{' '}
              <span style={{ color: '#58A6FF' }}>GitHub Copilot</span>
            </p>
            <p style={{ fontSize: 12, color: '#30363D' }}>
              © 2024 Mysteria AI — Microsoft Agents League Hackathon
            </p>
          </motion.div>
        </motion.section>

      </div>
    </div>
  )
}
