import { useEffect, useRef } from 'react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'

const genres = [
  { id: 'campus',     emoji: '🎓', name: 'Campus Crimes',    cases: 'Missing student, Hackathon sabotage, Stolen research' },
  { id: 'cyberpunk',  emoji: '🤖', name: 'Cyberpunk',        cases: 'AI rebellion, Data theft, Corporate conspiracy' },
  { id: 'fantasy',    emoji: '👑', name: 'Fantasy Kingdom',  cases: 'Royal assassination, Magic theft, Dragon crime' },
  { id: 'space',      emoji: '🚀', name: 'Space Station',    cases: 'Sabotage, Alien infiltration, Missing scientist' },
  { id: 'historical', emoji: '🏛️', name: 'Historical',       cases: 'Victorian murder, Ancient betrayal, War secrets' },
  { id: 'horror',     emoji: '👻', name: 'Horror',           cases: 'Haunted mansion, Supernatural disappearance' },
]

const features = [
  { icon: '🧠', title: 'AI Characters That Lie',  desc: 'Suspects remember what you asked and change their story when cornered with evidence.' },
  { icon: '♾️', title: 'Infinite Cases',           desc: 'Every mystery is uniquely generated by AI. No two cases are ever the same.' },
  { icon: '⚖️', title: 'Solve or Fail',            desc: 'Wrong accusations cost you detective rank. Only the truth will set you free.' },
]

const staggerContainer = { hidden: {}, visible: { transition: { staggerChildren: 0.1 } } }
const fadeUp = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0, transition: { duration: 0.55, ease: 'easeOut' } } }

const Orb = ({ style, animate }) => (
  <motion.div
    animate={animate}
    transition={{ duration: 25, repeat: Infinity, ease: 'easeInOut', repeatType: 'mirror' }}
    style={{ position: 'absolute', borderRadius: '50%', filter: 'blur(72px)', pointerEvents: 'none', ...style }}
  />
)

// Animated particle canvas
function ParticleCanvas() {
  const canvasRef = useRef(null)

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')

    let width = canvas.width = window.innerWidth
    let height = canvas.height = window.innerHeight

    const COUNT = 80
    const particles = Array.from({ length: COUNT }, () => ({
      x: Math.random() * width,
      y: Math.random() * height,
      r: Math.random() * 1.5 + 0.4,
      vx: (Math.random() - 0.5) * 0.25,
      vy: (Math.random() - 0.5) * 0.25,
      alpha: Math.random() * 0.5 + 0.1,
    }))

    let rafId
    function draw() {
      ctx.clearRect(0, 0, width, height)
      for (const p of particles) {
        p.x += p.vx
        p.y += p.vy
        if (p.x < 0) p.x = width
        if (p.x > width) p.x = 0
        if (p.y < 0) p.y = height
        if (p.y > height) p.y = 0

        ctx.beginPath()
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2)
        ctx.fillStyle = `rgba(139,92,246,${p.alpha})`
        ctx.fill()
      }
      rafId = requestAnimationFrame(draw)
    }
    draw()

    function onResize() {
      width = canvas.width = window.innerWidth
      height = canvas.height = window.innerHeight
    }
    window.addEventListener('resize', onResize)
    return () => { cancelAnimationFrame(rafId); window.removeEventListener('resize', onResize) }
  }, [])

  return (
    <canvas
      ref={canvasRef}
      style={{ position: 'fixed', inset: 0, zIndex: 0, pointerEvents: 'none', opacity: 0.6 }}
    />
  )
}

export default function Landing() {
  const navigate = useNavigate()

  return (
    <div style={{ backgroundColor: '#0A0A0F', minHeight: '100vh', color: '#F8FAFC', fontFamily: 'Inter, sans-serif', overflowX: 'hidden' }}>

      {/* ── Particles ── */}
      <ParticleCanvas />

      {/* ── Ambient orbs ── */}
      <div style={{ position: 'fixed', inset: 0, zIndex: 0, overflow: 'hidden', pointerEvents: 'none' }}>
        <Orb animate={{ x: [0, 50, -30, 0], y: [0, -60, 40, 0] }}
          style={{ top: '5%', left: '8%', width: 520, height: 520, background: 'radial-gradient(circle, rgba(139,92,246,0.22) 0%, transparent 70%)' }} />
        <Orb animate={{ x: [0, -60, 40, 0], y: [0, 50, -30, 0] }}
          style={{ top: '35%', right: '5%', width: 440, height: 440, background: 'radial-gradient(circle, rgba(20,184,166,0.16) 0%, transparent 70%)' }} />
        <Orb animate={{ x: [0, 30, -50, 0], y: [0, 60, -20, 0] }}
          style={{ bottom: '8%', left: '28%', width: 380, height: 380, background: 'radial-gradient(circle, rgba(139,92,246,0.12) 0%, transparent 70%)' }} />
      </div>

      {/* ══ HERO ══ */}
      <section style={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        padding: '0 24px',
        position: 'relative',
        zIndex: 1,
      }}>
        <motion.div initial="hidden" animate="visible" variants={staggerContainer} style={{ maxWidth: 780, width: '100%' }}>

          {/* Headline */}
          <motion.h1
            variants={fadeUp}
            style={{
              fontFamily: 'Cinzel, serif',
              fontSize: 'clamp(2.8rem, 9vw, 5.8rem)',
              fontWeight: 700,
              lineHeight: 1.08,
              marginBottom: 28,
              background: 'linear-gradient(140deg, #ffffff 0%, #d8b4fe 45%, #8B5CF6 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            Every Case.<br />Completely Unique.
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            variants={fadeUp}
            style={{ fontSize: 'clamp(1rem, 2.5vw, 1.15rem)', color: '#94A3B8', lineHeight: 1.85, maxWidth: 580, margin: '0 auto 52px' }}
          >
            Enter an AI-generated mystery world. Interrogate suspects, collect evidence, and solve the case.
            No two mysteries are ever the same.
          </motion.p>

          {/* Single centered CTA */}
          <motion.div variants={fadeUp} style={{ display: 'flex', justifyContent: 'center' }}>
            <motion.button
              whileHover={{ scale: 1.06, boxShadow: '0 0 40px rgba(139,92,246,0.6)' }}
              whileTap={{ scale: 0.96 }}
              onClick={() => navigate('/generate')}
              style={{
                backgroundColor: '#8B5CF6',
                color: '#fff',
                border: 'none',
                borderRadius: 12,
                padding: '18px 52px',
                fontSize: 17,
                fontWeight: 600,
                cursor: 'pointer',
                fontFamily: 'Inter, sans-serif',
                letterSpacing: '0.02em',
              }}
            >
              Start Investigating →
            </motion.button>
          </motion.div>
        </motion.div>

        {/* Scroll hint */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.2, duration: 0.6 }}
          style={{ position: 'absolute', bottom: 40, color: '#334155', fontSize: 12, letterSpacing: '0.1em', textTransform: 'uppercase' }}
        >
          scroll to explore ↓
        </motion.div>
      </section>

      {/* ══ GENRE SECTION ══ */}
      <section style={{ padding: '80px 24px', position: 'relative', zIndex: 1 }}>
        <div style={{ maxWidth: 1160, margin: '0 auto' }}>
          <motion.h2
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}
            style={{ fontFamily: 'Cinzel, serif', fontSize: 'clamp(1.6rem, 4vw, 2.4rem)', textAlign: 'center', marginBottom: 16, color: '#F8FAFC' }}
          >
            Choose Your World
          </motion.h2>
          <motion.p
            initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: 0.2, duration: 0.5 }}
            style={{ textAlign: 'center', color: '#64748B', fontSize: 14, marginBottom: 52 }}
          >
            Each genre generates completely different suspects, crimes, and motives.
          </motion.p>

          <motion.div
            variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-60px' }}
            style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(290px, 1fr))', gap: 20 }}
          >
            {genres.map((genre) => (
              <motion.div
                key={genre.id} variants={fadeUp}
                whileHover={{ y: -8, boxShadow: '0 0 0 1px rgba(139,92,246,0.65), 0 24px 48px rgba(139,92,246,0.14)' }}
                onClick={() => navigate('/generate')}
                style={{ backgroundColor: '#12121A', border: '1px solid #1E1E2E', borderRadius: 16, padding: '28px 24px', cursor: 'pointer' }}
              >
                <div style={{ fontSize: 38, marginBottom: 14, lineHeight: 1 }}>{genre.emoji}</div>
                <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: 17, fontWeight: 600, marginBottom: 8, color: '#F8FAFC' }}>{genre.name}</h3>
                <p style={{ fontSize: 13, color: '#475569', lineHeight: 1.65 }}>{genre.cases}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ══ FEATURES SECTION ══ */}
      <section style={{ padding: '80px 24px 100px', position: 'relative', zIndex: 1 }}>
        <div style={{ maxWidth: 1160, margin: '0 auto' }}>
          <motion.h2
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.6 }}
            style={{ fontFamily: 'Cinzel, serif', fontSize: 'clamp(1.5rem, 3.5vw, 2.2rem)', textAlign: 'center', marginBottom: 52, color: '#F8FAFC' }}
          >
            How It Works
          </motion.h2>
          <motion.div
            variants={staggerContainer} initial="hidden" whileInView="visible" viewport={{ once: true, margin: '-60px' }}
            style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 28 }}
          >
            {features.map((f) => (
              <motion.div
                key={f.title} variants={fadeUp}
                style={{ backgroundColor: '#12121A', border: '1px solid #1E1E2E', borderRadius: 16, padding: '36px 28px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}
              >
                <div style={{ position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)', width: 120, height: 1, background: 'linear-gradient(90deg, transparent, rgba(139,92,246,0.6), transparent)' }} />
                <div style={{ fontSize: 42, marginBottom: 18 }}>{f.icon}</div>
                <h3 style={{ fontFamily: 'Cinzel, serif', fontSize: 17, fontWeight: 600, marginBottom: 14, color: '#F8FAFC' }}>{f.title}</h3>
                <p style={{ fontSize: 14, color: '#64748B', lineHeight: 1.75 }}>{f.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* ══ FOOTER ══ */}
      <footer style={{ textAlign: 'center', padding: '32px 24px', borderTop: '1px solid #1E1E2E', color: '#334155', fontSize: 13, position: 'relative', zIndex: 1, letterSpacing: '0.02em' }}>
        Powered by Azure AI Foundry
      </footer>
    </div>
  )
}
